language: java
sudo: false

addons:
  sonarqube:
    organization: "apatiati-github"
    sonarqube:
      token: $SONAR_TOKEN
    branches:
      - development
    
jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
