language: java
sudo: false

addons:
  sonarqube:
    organization: "apatiati-github"
    token:
      secure: $SONAR_TOKEN	
    branches:
      - master
      - development
    
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
