language: java
sudo: false

addons:
  sonarqube:
    organization: "apatiati-github"
    sonarqube:
      token: $SONAR_TOKEN
    
jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=apatiati-github

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
